apiVersion: v1
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.podName }}-db
  namespace: {{ .Values.namespace }}
  labels:
    k8s-app: {{ .Values.podName }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: {{ .Values.podName }}-db
  template:
    metadata:
      labels:
        k8s-app: {{ .Values.podName }}-db
    spec:
      imagePullSecrets:
      - name: {{ .Values.pullSecret }}
      containers:
      - image: {{ .Values.DBimage }}
        name: {{ .Values.podName }}-db
        imagePullPolicy: Always
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgresDBuser }}
        - name: POSTGRES_DB
          value: {{ .Values.postgresDBname }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgresDBpassword }}
        - name:  PGDATA
          value: /var/lib/postgresql/data/pgdata/
        volumeMounts:
        - name: db-folder
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-folder
          persistentVolumeClaim:
            claimName: {{ .Release.Namespace }}-db
